# Generated by Django 2.2.1 on 2019-08-28 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('design_requested_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Solicitado')),
                ('design_name', models.CharField(max_length=50, verbose_name='Nombre del Diseño')),
                ('design_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Diseñador')),
            ],
            options={
                'verbose_name': 'Diseño',
                'verbose_name_plural': 'Diseños',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_type', models.CharField(max_length=20, verbose_name='Tipo de Estado')),
                ('state_description', models.CharField(max_length=20, verbose_name='Estado')),
                ('state_order', models.IntegerField(verbose_name='Orden de Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='Nombre Proyecto')),
                ('project_description', models.TextField(max_length=4000, verbose_name='Descripción de Proyecto')),
                ('project_payment_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor a Pagar')),
                ('project_create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('project_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Enterprise', verbose_name='Empresa')),
                ('project_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.State', verbose_name='Estado del Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_original', models.ImageField(blank=True, null=True, upload_to='originals/', verbose_name='Diseño Original')),
                ('image_processed', models.ImageField(blank=True, null=True, upload_to='processed/', verbose_name='Diseño Procesado')),
                ('image_design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='designs.Design')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
            },
        ),
        migrations.AddField(
            model_name='design',
            name='design_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.Project', verbose_name='Proyecto del Diseño'),
        ),
        migrations.AddField(
            model_name='design',
            name='design_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.State', verbose_name='Estado del Diseño'),
        ),
    ]
